# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='timings',
        ),
        migrations.AddField(
            model_name='events',
            name='end_timings',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_timings',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='week_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.CharField(choices=[('Past', 'Past'), ('Current', 'Current'), ('Upcoming', 'Upcoming')], max_length=1),
        ),
    ]
