# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_auto_20170926_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end_timings',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_timings',
            new_name='start_time',
        ),
    ]
