# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_auto_20170926_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='guest',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
