# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 16:40
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0006_auto_20170926_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='week_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=56, null=True),
        ),
    ]
