# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-29 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_auto_20170927_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='guest',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
