# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0009_auto_20170929_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='guest',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
