# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(max_length=100, null=True)),
                ('instructor', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField(max_length=100, null=True)),
                ('end_date', models.DateField(max_length=100, null=True)),
                ('week_days', models.CharField(max_length=100, null=True)),
                ('timings', models.CharField(max_length=100, null=True)),
                ('venue', models.TextField(max_length=500, null=True)),
                ('contact_persons', models.CharField(max_length=1000, null=True)),
                ('poster', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(max_length=10000, null=True)),
                ('status', models.CharField(choices=[('P', 'Past'), ('C', 'Current'), ('U', 'Upcoming')], max_length=1, null=True)),
            ],
        ),
    ]
