# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='poster',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='activities',
            name='status',
            field=models.CharField(choices=[('Past', 'Past'), ('Current', 'Current'), ('Upcoming', 'Upcoming')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='week_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=56, null=True),
        ),
    ]
