# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_auto_20170921_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='poster',
            field=models.FileField(null=True, upload_to='activities/'),
        ),
    ]
