# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0004_auto_20170921_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='poster',
            field=models.FileField(upload_to='activities/'),
        ),
    ]
