# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0005_auto_20170922_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='timings',
        ),
        migrations.AddField(
            model_name='activities',
            name='end_timings',
            field=models.TimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='start_timings',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
