# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorized_Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('board', models.CharField(choices=[('PRIEST', 'PRIEST'), ('TRUST', 'TRUST'), ('EXECUTIVE', 'EXECUTIVE')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('associated_members', models.ManyToManyField(to='About_Us.Authorized_Members')),
            ],
        ),
    ]
