# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About_Us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorized_members',
            name='board',
            field=models.CharField(choices=[('PRIEST', 'PRIEST'), ('TRUST', 'TRUST'), ('EXECUTIVE', 'EXECUTIVE')], max_length=10),
        ),
    ]
