# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(max_length=10)),
                ('path', models.CharField(max_length=500)),
            ],
        ),
    ]
