# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 19:11
from __future__ import unicode_literals

import Publications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publications', '0004_auto_20170920_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='file',
            field=models.FileField(null=True, upload_to=Publications.models.user_directory_path),
        ),
    ]
